---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../group_vars/all/vault.yaml
  vars:
    vm_list:
      - { name: "k3s-01", id: "241" }
      - { name: "k3s-02", id: "242" }
      - { name: "k3s-03", id: "243" }
      - { name: "k3s-04", id: "244" }
      - { name: "k3s-05", id: "245" }
      - { name: "k3s-06", id: "246" }
      - { name: "k3s-07", id: "247" }
      - { name: "k3s-08", id: "248" }
      - { name: "k3s-09", id: "249" }
      - { name: "k3s-10", id: "250" }

  tasks:
    - name: Stop VM (if running)
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host_ip }}"
        api_user: "ansible@pam"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        node: pve2
        vmid: "{{ item.id }}"
        state: stopped
        timeout: 300
      loop: "{{ vm_list }}"

    - name: Update CPU/RAM on each VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host_ip }}"
        api_user: "ansible@pam"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        node: pve2
        vmid: "{{ item.id }}"
        state: present
        sockets: 1
        cores: 8
        memory: 16384
        cpu: host
        tags: ['ubuntu','k3s']
        timeout: 300
        update: true
      loop: "{{ vm_list }}"

    - name: Start VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host_ip }}"
        api_user: "ansible@pam"
        api_token_id: "{{ proxmox_token_id }}"
        api_token_secret: "{{ proxmox_token_secret }}"
        node: pve2
        vmid: "{{ item.id }}"
        state: started
        timeout: 300
      loop: "{{ vm_list  }}"
