---
# add-longhorn-disk.yaml
- hosts: localhost
  gather_facts: false
  vars:
    pve_node_name: pve2
    pve_node_ip: 192.168.2.112
    pve_node_user: root                      # or an unprivileged user with sudo
    pve_node_key: /home/bob/.ssh/id_ed25519
    storage: local-lvm
    disk_size_gb: 100
    vm_list:
      - { vmid: 241 }
      - { vmid: 242 }
      - { vmid: 243 }
      - { vmid: 244 }
      - { vmid: 245 }

  pre_tasks:
    - name: Define Proxmox node as a delegate host
      add_host:
        name: "{{ pve_node_name }}"
        ansible_host: "{{ pve_node_ip }}"
        ansible_user: "{{ pve_node_user }}"
        ansible_ssh_private_key_file: "{{ pve_node_key }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Ensure SCSI controller is virtio-scsi-single (safe to re-run)
      delegate_to: "{{ pve_node_name }}"
      become: true
      ansible.builtin.command: >
        qm set {{ item.vmid }} -scsihw virtio-scsi-single
      loop: "{{ vm_list }}"

    - name: Add a new SCSI disk for Longhorn (scsi1) with discard/ssd/iothread
      delegate_to: "{{ pve_node_name }}"
      become: true
      ansible.builtin.command: >
        qm set {{ item.vmid }}
        -scsi1 {{ storage }}:{{ disk_size_gb }},discard=on,ssd=1,iothread=1
      loop: "{{ vm_list }}"
